### PR TITLE
Create `ToInvertedResult` extension methods on Maybe

### PR DESCRIPTION
**Pull request by bothzoli**
Added `ToInvertedResult` methods and corresponding tests to `Maybe`.
As a housekeeping effort, removed some potentially superfluous test files.

`ToInvertedResult` method returns a `Success` result from a `None` value and a `Failure` result from a `Some` value.

Resolves: #571

### CODE REVIEW

**Comment by bothzoli** [comment]
So I based the tests on the tests for `ToResult` and tried to keep them consistent.
That's when I realised that some of the `ToResult` tests (with `Left` in the name) were most likely some copy-paste because they didn't execute other code paths than the other tests.
As a housekeeping commit I thought I'd clean them up to be consistent with the new `ToInvertedResult`.
I'm happy to undo that commit if needed, but I think it just removes code that shouldn't have been there in the first place.

**Comment by DerStimmler** [comment]
Ah, I see. Then that should be fine.
Following the scout rule here 😄

**Comment by vkhorikov** [comment]
@bothzoli Looks like there are some merge conflicts, could you take a look?

**Comment by bothzoli** [comment]
Sure, I'll take a look once I recover from Christmas food coma 😇

**Comment by bothzoli** [comment]
@vkhorikov I fixed the merge conflict, but also since the target branch has changed a bit with #576 I extended `ToInvertedResult` to also have the lazy error overloads.
I found that the unit tests in #576 did not assert the calling of the lazy error function, so I unified all those tests to do that.
I also found that the `ToUnitResult` extensions were not overloaded with the lazy error creation, so I added it there too.

This PR became a bit more complicated than I imagined it to be, but I think overall the code base became more consistent.

**Comment by vkhorikov** [comment]
Thank you!

**Pull request merged**
