### PR TITLE
Add editorconfig file

### PR DESCRIPTION
**Pull request by vinibeloni**
Hello,

I was looking for repos to contribute when I found this project.
I believe it's good practice in .NET projects to have a code style (whatever it is), so I tried to adapt this file to the project's convention.

If you run `dotnet format` the 353 files will be changed, but all the changes will just be: spaces removed, add newline, etc.

So I hope this contribution helps.

### CODE REVIEW

**Comment by vkhorikov** [comment]
Thank you for the contribution. Just for future reference: so many changed files mean the config contains formatting rules contrary to the ones that already (implicitly) exist in the code base. But still, some editorconfig is better than none, and we can adjust it moving forward.

**Comment by vinibeloni** [comment]
Thanks!

> Just for future reference: so many changed files mean the config contains formatting rules contrary to the ones that already (implicitly) exist in the code base.

Yes, sure. I tried to follow the existing codebase, I believe the editorconfig is very close to the current code style, but some details need to be tweaked for sure 😄 

can you add the `hacktoberfest-accepted` label please?

**Comment by hankovich** [comment]
@vinibeloni

> can you add the hacktoberfest-accepted label please?

This repo contains the `hacktoberfest` label, it should be enough to count this PR as a contribution to Hacktoberfest.

**Comment by hankovich** [comment]
That's weird. As I see the description says it should either be merged or marked as accepted or approved. As it's merged I assume that adding a label is not required.

Anyway, I've added the corresponding label. Please notify if it helps.

**Pull request merged**
