### PR TITLE
Adding TapTry and TapTryIf, as well as missing documentation for existing methods.

### PR DESCRIPTION
**Pull request by tinytownsoftware**

### CODE REVIEW

**Comment by vkhorikov** [comment]
Sorry for the delay. Merging. Thank you.

**Comment by tinytownsoftware** [comment]
Thank you! What does the release schedule look like?

**Comment by vkhorikov** [comment]
It's been published with v2.39.1. I normally publish a new version right after a merge.

**Comment by tinytownsoftware** [comment]
Excellent, thank you!

**Pull request merged**
