### PR TITLE
add support for maybe linq-like select chaining

### PR DESCRIPTION
**Pull request by pilotMike**
allows 
```
Maybe<int> result = from a in maybe1 from b in maybe2 select a + b;
```

### CODE REVIEW

**Comment by pilotMike** [comment]
allows 
```
Maybe<int> result = from a in maybe1 from b in maybe2 select a + b;
```

**Comment by vkhorikov** [comment]
Merged, thanks.

**Comment by SuperJMN** [comment]
Is this available for Result<T> and Result<T,E>

E.g.

```csharp
var query = from r in someResult
  from s in someOtheResult
  select new { r, s };
```

**Comment by hankovich** [comment]
@SuperJMN It's available for `Result<T>` and `Result<T, E>`, but `Result` and `UnitResult<E>` are not (obviously) supported.

**Pull request merged**
