### PR TITLE
Add Combine extension methods (#79)

### PR DESCRIPTION
**Pull request by ahryshchanka**

### CODE REVIEW

**Comment by hankovich** [comment]
Hi, I understand that you added only mentioned overloads, but I think we need to have more overloads.
What do you think about:

1. IEnumerable<Task<Result>> / IEnumerable<Task<Result<T>>>
2. Task<IEnumerable<Result>> / Task<IEnumerable<Result<T>>>
3. Task<IEnumerable<Task<Result>> /  Task<IEnumerable<Task<Result<T>>> (Wow)
4. What should we do with Result<T, TError>?
5. Sometimes in case of IEnumerable<T> we don't want to see Result<IEnumerable<T>>, but we want to have Result<IEnumerable<TNew>>, so
```public static Result<IEnumerable<TNew>> Combine<T, TNew>(this IEnumerable<Result<T>> results, Func<T, TNew> mapper```
6. We should also have ability to compose resulted IEnumerable to a single object (like `SelectMany` does)
```public static Result<TResult> Combine<TValue, TResult>(this IEnumerable<Result<TValue>> results, Func<IEnumerable<TValue>, TResult> composer)```
7. Overloads without errorMessagesSeparator should be added as well (You should use ", " as a default separator)

**Comment by grishchenkoa** [comment]
`async Task<Result> Combine(this IEnumerable<Task<Result>> tasks, string errorMessageSeparator, bool continueOnCapturedContext = true)` method added

**Comment by grishchenkoa** [comment]
@vkhorikov and @hankovich I think I did all required changes and code ready for review

**Comment by grishchenkoa** [comment]
@hankovich 
```
Result<IEnumerable<TNew>> Combine<T, TNew>(this IEnumerable<Result<T>> results, Func<T, TNew> mapper)
```
looks like combination of two functions: `.Combine().Map(mapper)`

**Comment by grishchenkoa** [comment]
> Overloads without errorMessagesSeparator should be added as well (You should use ", " as a default separator)
for this implementation i saw special task [https://github.com/vkhorikov/CSharpFunctionalExtensions/issues/66](66)

**Pull request merged**
