### PR TITLE
Revert "Update to netstandard 1.3, added ISerializable"

### PR DESCRIPTION
**Pull request by solvingJ**
Waiting 6 days until netstandard 2.0 comes out to add tests.  Netstandard 2.0 contains the necessary BinaryFormatter not currently available in netstandard 1.x

### CODE REVIEW

**Comment by vkhorikov** [comment]
It seems that there's no need to serialize both IsFailure and IsSuccess. Could you adjust the code so that only one of them gets serialized?

**Comment by solvingJ** [comment]
I actually thought about it both ways and still see both sides. One could make same argument for existence of both vars in the original struct. Why have both? its just sugar with very little value. 

I actually decided I DO like having both in the struct, but that wasn't why I included both in serialization. 

Ultimately I realized that the serialized version should include all non-null members of the original for consistency and predictablility.  Choosing to eliminate one actually seems l arbitrary after thinking about it for a bit.

 Also, without both, when deserializing, one would have to go through the troubles of polymorphic deserializing, choosing between separate "SuccessResult" and FailedResult" objects , which again aren't consistent with the original struct.

**Comment by vkhorikov** [comment]
Merged the pull request. Could you add some tests for this functionality?

**Comment by solvingJ** [comment]
Yes, I believe Netcore and Netstandard will be out on May 10 which will bring BinaryFormatter. This will give an effective way to test serialization without bringing in dependencies. If there's a different way to test serialization now, I couldn't find it :(

**Pull request merged**
