### PR TITLE
Fix script uploading release assets

### PR DESCRIPTION
**Pull request by bothzoli**
Fix the script that uploads the release assets.
The script used PowerShell syntax, but the step was actually using `bash`.

Fixes: #590

### CODE REVIEW

**Comment by bothzoli** [comment]
@vkhorikov I honestly hope this will fix the asset upload.

**Comment by vkhorikov** [comment]
Yep, merging this.

**Comment by bothzoli** [comment]
I know this is a minor thing and it's not really that important, but I'm glad it works now \o/

**Comment by vkhorikov** [comment]
I'm glad too, it was broken for a long long time, thanks for fixing it!

**Pull request merged**
