### PR TITLE
Remove EOL .Net Frameworks.

### PR DESCRIPTION
**Pull request by xavierjohn**
Remove EOL .Net Frameworks and obsolete methods
https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework

.NET Framework 4.0,  EOL: Jan 12, 2016
.NET Framework 4.5,  EOL: Jan 12, 2016
.NET Framework 4.6.1 EOL: Apr 26, 2022

### CODE REVIEW

**Comment by hankovich** [comment]
.NET 5 is also out of support

**Comment by vkhorikov** [comment]
We should, yes. `ValueObject < T >` is no longer obsolete, it supports a use case which is not available for the regular VO.

**Comment by bothzoli** [comment]
I fixed the merge conflicts in #554.

**Comment by bothzoli** [comment]
With #554 merged I believe this PR could be closed.
Sorry @xavierjohn, I didn't intend to steal your thunder 🥺

**Pull request closed without merging**
