### PR TITLE
Create strong named assembiles

### PR DESCRIPTION
**Pull request by bothzoli**
# Create strong named NuGet package

To create a strong named NuGet package, a new project `CSharpFunctionalExtensions.StrongName` was added to the solution.
The project references source files from `CSharpFunctionalExtensions.csproj` and it uses the generated signing key (`CSharpFunctionalExtensions.snk`) to sign the assembly.

The `Dockerfile` was updated so that a strong named NuGet package is also built.
The `azure-pipelines.yml` was also modified so that the newly created package is uploaded as both a GitHub release asset and to nuget.org as well.

Minor fixes were applied to the `azure-pipelines.yml` file:
- the authorization header should have `Bearer` instead of token based on the [documentation](https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28#upload-a-release-asset)
- the `cURL` upload should use the `--data-binary` switch (note that nuget packages were not added to previous releases either)
- run conditions were added to the publish steps so that the pipeline won't fail if the credentials are not provided, but simply skip the publish steps

The version file `version.txt` was also updated with a patch version bump.

Fixes: #27

### CODE REVIEW

**Comment by hankovich** [comment]
New csproj is just a copy of the existing one. I suggest you to move common properties to Directory.Build.props

**Comment by bothzoli** [comment]
Oh yeah, thanks mate. I knew something was amiss.
I'll update the PR shortly.

**Comment by bothzoli** [comment]
I wonder though, wouldn't a `Directory.Build.props` be imported into all projects including `Examples`, `Tests`?
I'm not sure that'd be correct.
Shall I separate the _main_ projects into an `src` folder?
Or use a different `.props` file and explicitly import where needed?

**Comment by bothzoli** [comment]
I've gone with a `Common.Build.props` file at the root of the solution.
Please let me know if you'd prefer a different approach.

**Comment by bothzoli** [comment]
Hey, any thoughts on the PR?
Thanks

**Comment by vkhorikov** [comment]
Hey, sorry, really short on time these days. I'll test it during the upcoming weekend and will push it "to prod" if everything looks good (which it does on the first glance).

**Comment by vkhorikov** [comment]
The current approach looks good, no need to include the common proj into examples and tests, those aren't getting published anyway. Locally everything looks good, merged it to master, let's see how the build goes.

**Comment by vkhorikov** [comment]
The pipeline has published the new nuget package successfully.

**Comment by bothzoli** [comment]
Wow, that's awesome news. I'll start using it right away.
Thank you very much 😊
I'll try to keep my eyes open, but if there are issues opened for the strong named package (that are working correctly with the _regular one_) feel free to tag me in the issue.

**Pull request merged**
